version: '3'
services:
  web:
    build: .
    command: bundle exec unicorn_rails -p 3000 -c /app/config/unicorn.rb
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3001:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.5
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306      
volumes:
  db-volume:
  bundle:
    driver: local